<?php

use App\GestationalAge;
use Illuminate\Database\Seeder;

class GestationalAgeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        GestationalAge::create([
            'name'=>'1'
        ]);
        GestationalAge::create([
            'name'=>'2'
        ]);
        GestationalAge::create([
            'name'=>'3'
        ]);
        GestationalAge::create([
            'name'=>'4'
        ]);
        GestationalAge::create([
            'name'=>'5'
        ]);
        GestationalAge::create([
            'name'=>'6'
        ]);
        GestationalAge::create([
            'name'=>'7'
        ]);
        GestationalAge::create([
            'name'=>'8'
        ]);
        GestationalAge::create([
            'name'=>'9'
        ]);
        GestationalAge::create([
            'name'=>'10'
        ]);
        GestationalAge::create([
            'name'=>'11'
        ]);
        GestationalAge::create([
            'name'=>'12'
        ]);
        GestationalAge::create([
            'name'=>'13'
        ]);
        GestationalAge::create([
            'name'=>'14'
        ]);
        GestationalAge::create([
            'name'=>'15'
        ]);
        GestationalAge::create([
            'name'=>'16'
        ]);
        GestationalAge::create([
            'name'=>'17'
        ]);
        GestationalAge::create([
            'name'=>'18'
        ]);
        GestationalAge::create([
            'name'=>'19'
        ]);
        GestationalAge::create([
            'name'=>'20'
        ]);
        GestationalAge::create([
            'name'=>'21'
        ]);
        GestationalAge::create([
            'name'=>'22'
        ]);
        GestationalAge::create([
            'name'=>'23'
        ]);
        GestationalAge::create([
            'name'=>'24'
        ]);
        GestationalAge::create([
            'name'=>'25'
        ]);
        GestationalAge::create([
            'name'=>'26'
        ]);
        GestationalAge::create([
            'name'=>'27'
        ]);
        GestationalAge::create([
            'name'=>'28'
        ]);
        GestationalAge::create([
            'name'=>'29'
        ]);
        GestationalAge::create([
            'name'=>'30'
        ]);
        GestationalAge::create([
            'name'=>'31'
        ]);
        GestationalAge::create([
            'name'=>'32'
        ]);
        GestationalAge::create([
            'name'=>'33'
        ]);
        GestationalAge::create([
            'name'=>'34'
        ]);
        GestationalAge::create([
            'name'=>'35'
        ]);
        GestationalAge::create([
            'name'=>'36'
        ]);
        GestationalAge::create([
            'name'=>'37'
        ]);
        GestationalAge::create([
            'name'=>'38'
        ]);
        GestationalAge::create([
            'name'=>'39'
        ]);
        GestationalAge::create([
            'name'=>'40'
        ]);
        GestationalAge::create([
            'name'=>'41'
        ]);
        GestationalAge::create([
            'name'=>'42'
        ]);
        GestationalAge::create([
            'name'=>'43'
        ]);
        GestationalAge::create([
            'name'=>'44'
        ]);
        GestationalAge::create([
            'name'=>'45+'
        ]);
    }
}
